// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CdnOrigin = {
  id: number;
  name: string;
  weight: number;
  priority: number;
  is_healthy: boolean;
};

export type EdgeActionEvent = {
  request: HttpRequest;
  origin_data: Array<CdnOrigin>;
  response: HttpResponse;
  hook_point: number;
  context: { [key in string]?: string };
  origin: OriginSelection;
};

export type HttpRequest = {
  uri: string;
  method: string;
  query_string: string;
  headers: { [key in string]?: string };
  body: string;
};

export type HttpResponse = {
  response_code: number;
  headers: { [key in string]?: string };
  body: string;
};

export type OriginSelection = { id: number };
